# Generated by Django 3.2.7 on 2022-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
